name: sendgrid_mailer
description: A Dart library used to compose and send emails using SendGrid v3 Mail Send API.
version: 0.2.0
homepage: https://github.com/dylanshine/sendgrid_mailer

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async: ^2.5.0
  http: ^1.0.0

dev_dependencies:
